name: QuasoPlugin
main: imp.crissyjuanxd.QuasoPlugin
version: ${project.version}
api-version: '26.2'
author: CrissyJuanXD
description: Plugin dedicado para el streamer Crosszy
commands:
  bloodmoon:
    description: Controla la BloodMoon y sus hordas.
    usage: /bloodmoon <show|start|stop|reload|spawnhorde>
    permission: bloodmoon.bloodmoon
    permission-message: 'No tienes permiso para usar este comando.'
  revive:
    description: Revive a player.
    usage: /revive <player>
    permission: viciont_hardcore3.revive
    permission-message: No tienes permiso para usar este comando.
  revivecoords:
    description: Configura las coordenadas del revive.
    usage: /revivecoords <x> <y> <z>
    permission: viciont_hardcore3.revivecoords
    permission-message: No tienes permiso para usar este comando.
  changes:
    description: Activa, desactiva o lista los cambios de cada etapa del server
    usage: /changes <activar|desactivar|list> [cambio]
    permission: quasoplugin.changes
    permission-message: No tienes permiso para usar este comando.
  ping:
    description: Muestra tu ping actual en milisegundos.
    usage: /ping
  ruletaqp:
    description: Comando para reproducir la animación de la ruleta.
    usage: /ruletaqp <json>
    permission: viciont_hardcore3.ruletavct
    permission-message: No tienes permiso para usar este comando.
  bonusvct:
    description: Comando para reproducir la animación de Bonus.
    usage: /bonusvct <json>
    permission: viciont_hardcore3.bonusvct
    permission-message: No tienes permiso para usar este comando.
  structure:
    description: Genera estructuras especiales en el mundo
    usage: /structure <nombre>
    permission: vicionthardcore3.command.estructure
    permission-message: No tienes permiso para usar este comando.
  lavaclash:
    description: Comando principal del evento LavaClash
    usage: /lavaclash <start|battle|force|reglas|resetpurple|end|list|add|remove>
    permission: viciont_hardcore3.command.lavaclash
    permission-message: No tienes permiso para usar este comando.
  buildbattle:
    description: Comando principal del evento BuildBattle
    usage: /buildbattle <start|tpzona|stick|addparcela|removeparcela|center|category|startbuild|endvote|resetbuild|reload|addvotador|removevotador|admin|addplayer|removeplayer|timeredit>
    permission: viciont_hardcore3.command.buildbattle
    permission-message: No tienes permiso para usar este comando.
  itemparty:
    description: Comando principal del evento ItemParty
    usage: /itemparty <start|end|reset|reload|castigo>
    permission: viciont_hardcore3.command.itemparty
    permission-message: No tienes permiso para usar este comando.
  hotpotato:
    description: Comando principal del evento HotPotato
    usage: /hotpotato <start|force|reglas|battle|stop|list|add|remove|reload>
    permission: viciont_hardcore3.command.hotpotato
    permission-message: No tienes permiso para usar este comando.
  logros:
    description: Comando para ver los logros.
    usage: /logros
  addlogro:
    description: Añade un logro a un jugador.
    usage: /addlogro <nombrelogro> <jugador> [item_lista|all]
    permission: viciont_hardcore3.command.addlogro
    permission-message: No tienes permiso para usar este comando.
  removelogro:
    description: Remueve un logro a un jugador.
    usage: /removelogro <nombrelogro> <jugador> [item_lista|all]
    permission: viciont_hardcore3.command.removelogro
    permission-message: No tienes permiso para usar este comando.
  magictp:
    description: Teletransporta jugadores a coordenadas especificadas con efectos especiales.
    usage: /magictp <jugador o @a> <x y z | spawn>
    permission: viciont_hardcore3.command.magic
    permission-message: No tienes permiso para usar este comando.
  spawnqp:
    description: Spawnea un mob personalizado en tu ubicación
    usage: /spawnqp <mob> [jugador (opcional)] [x] [y] [z]
    permission: viciont_hardcore3.command.spawnvct
    permission-message: No tienes permiso para usar este comando.
  timers:
    description: Comando General para crear, editar, remover y ver timers.
    usage: /timers <crear|editar|remover|lista>
    permission: viciont_hardcore3.command.addtiempo
    permission-message: No tienes permiso para usar este comando.
  giveqp:
    description: Da un item especial del plugin a un jugador.
    usage: /giveqp <item> [cantidad] [jugador]
    permission: viciont_hardcore3.command.givevct
    permission-message: No tienes permiso para usar este comando.
  addnightmare:
    description: Añade el evento Nightmare a un jugador o a todos.
    usage: /addnightmare <player|@a>
    permission: viciont_hardcore3.command.addnightmare
    permission-message: No tienes permiso para usar este comando.
  removenightmare:
    description: Remueve el evento Nightmare a un jugador o a todos.
    usage: /removenightmare <player|@a>
    permission: viciont_hardcore3.command.removenightmare
    permission-message: No tienes permiso para usar este comando.
  resetnightmarecooldown:
    description: Resetea el cooldown del evento Nightmare a un jugador o a todos.
    usage: /resetnightmarecooldown <player|@a>
    permission: viciont_hardcore3.command.resetnightmarecooldown
    permission-message: No tienes permiso para usar este comando.
  levelnightmare:
    description: Ajusta el nivel de la pesadilla
    usage: /levelnightmare <jugador|@a> <Nvl1/Nvl2/Nvl3>
    permission: viciont_hardcore3.command.levelnightmare
    permission-message: No tienes permiso para usar este comando.
  missions:
    description: Comando administrativo para misiones.
    usage: /missions
    permission: viciont_hardcore3.missions.admin
    permission-message: No tienes permiso para usar este comando.
  misiones:
    description: Abre la interfaz del sistema de misiones
    usage: /misiones
  mobcap:
    description: Comando principal para gestionar MobCap
    usage: /mobcap <info|setbase|doble|triple|normal|habilitar|deshabilitar|reset|reload|mob>
    permission: viciont_hardcore3.mobcap.admin
    aliases: [ mc, mobcapmanager ]
  mobcapinfo:
    description: Muestra información detallada del MobCap
    usage: /mobcapinfo
    permission: viciont_hardcore3.mobcap.admin
    aliases: [ mcinfo, mobcapstatus ]
  habilidades:
    description: Muestra las habilidades desbloqueadas de un jugador
    usage: /habilidades <jugador>
    permission: viciont_hardcore3.command.habilidades
    permission-message: No tienes permiso para usar este comando.
  debugarena:
    description: Activa el modo debug de arenas.
    usage: /debugarena
    permission: viciont_hardcore3.command.debugarena
    permission-message: No tienes permiso para usar este comando.
  altarvct:
    description: Comando para administrar los Altares.
    usage: /altarvct <info|create|addcooldown|delcooldown>
    permission: viciont_hardcore3.command.altarcreate
    permission-message: No tienes permiso para usar este comando.
  pvp:
    description: Activa o desactiva el PVP.
    usage: /pvp <activate|deactivate>
    permission: viciont_hardcore3.command.pvp
    permission-message: No tienes permiso para usar este comando.
  proteccion:
    description: Obtiene la guía de protecciones
    usage: /proteccion
  mochilas:
    description: Comando para administrar mochilas
    usage: /mochilas <jugador>
    permission: viciont_hardcore3.command.mochilas
    permission-message: No tienes permiso para usar este comando.
  dinocoins:
    description: Consulta y administra las DinoCoins físicas en monederos.
    usage: /dinocoins <add|remove|get> <jugador> [cantidad]
    permission: dinocoins.admin
    permission-message: No tienes permiso para usar este comando.
  delmochilas:
    description: Elimina las mochilas de un jugador
    usage: /delmochilas <jugador>
    permission: viciont_hardcore3.command.mochilas
  casino:
    description: Abre la interfaz del casino
    usage: /casino <set/reload/slot/remove> <blackjack/slot>
    permission: viciont_hardcore3.command.casino
    permission-message: No tienes permiso para usar este comando.
  anuncio:
    description: Envia un anuncio global con formato personalizado.
    usage: /anuncio <mensaje>
    permission: viciont_hardcore3.command.anuncio
    permission-message: No tienes permiso para usar este comando.
  itempartycastigo:
    description: Administrar castigos del evento ItemParty
    usage: /itempartycastigo remove <jugador>
    permission: itemparty.admin
  bosstp:
    description: Tepea a la zona del Boss
    usage: /bosstp
  setbossspawn:
    description: Establece el spawn del Boss
    usage: /setbossspawn
    permission: viciont_hardcore3.command.setbossspawn
    permission-message: No tienes permiso para usar este comando.
  givestatue:
    description: Comando para configurar las Estatuas de efectos.
    aliases: [statue]
    usage: /givestatue [give|clone|debug]
    permission: viciont_hardcore3.command.givestatue
    permission-message: No tienes permiso para usar este comando.
  givespawner:
    description: Da un spawner personalizado que genera mobs custom.
    usage: /givespawner <mob> [jugador] | /givespawner vanilla <mob_vanilla> [jugador]
    permission: viciont_hardcore3.command.givespawner
    permission-message: No tienes permiso para usar este comando.
  reloadcustomspawn:
    description: Recarga todos los spawners custom en el mundo
    usage: /reloadcustomspawn
    permission: viciont_hardcore3.command.givespawner
    permission-message: No tienes permiso para usar este comando.
  quasoreload:
    description: Recarga la configuración del plugin
    usage: /quasoreload
    permission: viciont_hardcore3.command.reload
    permission-message: No tienes permiso para usar este comando.
  spawnshop:
    description: Spawnea una tienda (aldeano) en las coordenadas especificadas
    usage: /spawnshop <nombre> [x] [y] [z]
    permission: viciont_hardcore3.shop.admin
    permission-message: No tienes permiso para usar este comando.
  trade:
    description: Comando para configurar trades de la ShopSystem
    usage: /trade <item> <cantidad>
    permission: viciont_hardcore3.command.trade
    permission-message: No tienes permiso para usar este comando.
  removeshop:
    description: Elimina un aldeano de la ShopSystem
    usage: /removeshop
    permission: viciont_hardcore3.command.removeshop
    permission-message: No tienes permiso para usar este comando.
  floor:
    description: Cambia el suelo de tu parcela al bloque que tienes en la mano.
    usage: /floor
  bubble:
    description: Activa o desactiva la burbuja de chat personalizada.
    usage: /bubble <start|stop>
    permission: viciont_hardcore3.command.bubble
    permission-message: No tienes permiso para usar este comando.
  wardencave:
    description: Comando unificado de la dimensión WardenCave
    usage: /wardencave <portal [remove] | join <jugador/@a> [spawn] | leave <jugador/@a> | boss <list/spawn>>
    permission: viciont_hardcore3.command.wardencave
    permission-message: No tienes permiso para usar este comando.
  tiendas:
    description: Te teletransporta a las tiendas.
  settiendas:
    description: Fija el spawn de las tiendas.
    usage: /settiendas
    permission: viciont_hardcore3.command.settiendas
    permission-message: No tienes permiso para usar este comando.
  spawn:
    description: Tepea al spawn central usando magia.
    usage: /spawn
  setspawn:
    description: Define el punto de spawn.
    usage: /setspawn
    permission: viciont_hardcore3.command.setspawn
    permission-message: No tienes permiso para usar este comando.
  sethome:
    description: Establecer tu casa
    usage: /sethome
  home:
    description: Ir a tu casa
    usage: /home
  delhome:
    description: Elimina tu casa
    usage: /delhome
  pesca:
    description: Gestiona las zonas de pesca custom
    usage: /pesca <give|set|reload|list>
    permission: viciont_hardcore3.command.pesca
    permission-message: No tienes permiso para usar este comando.
  tumba:
    description: Ver la lista de tus tumbas activas
    usage: /tumba
  tumbas:
    description: Comando de administrador de tumbas
    usage: /tumbas <list|remove|place|reload>
    permission: viciont_hardcore3.command.tumbas
    permission-message: No tienes permiso para usar este comando.
  autoanuncio:
    description: Inicia una ráfaga de tips en el chat cada 30 segundos.
    usage: /autoanuncio
    permission: viciont_hardcore3.command.autoanuncio
    permission-message: No tienes permiso para usar este comando.
  mantenimiento:
    description: Enciende o apaga el modo mantenimiento.
    usage: /mantenimiento <on|off>
    permission: viciont_hardcore3.mantenimiento
    permission-message: No tienes permiso para usar este comando.

depend: [EliteMobs]
softdepend: [FastAsyncWorldEdit, WorldGuard]

permissions:
  bloodmoon.bloodmoon:
    default: true
    description: Permite usar el comando BloodMoon.
  bloodmoon.show:
    default: true
    description: Permite consultar cuándo comienza la próxima BloodMoon.
  bloodmoon.start:
    default: op
  bloodmoon.stop:
    default: op
  bloodmoon.reload:
    default: op
  bloodmoon.spawnhorde:
    default: op
